import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/ThemeContext"; // Impor ThemeProvider dari konteks
import Script from "next/script"; // Import Script component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Keong Sumber Makmur",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics */}
        <Script
          strategy="afterInteractive" // Ensures the script loads after the page is interactive
          src="https://www.googletagmanager.com/gtag/js?id=G-RCQR3DG6HP"
          id="google-analytics-script" // Add unique ID for the external script
        />
        <Script
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-RCQR3DG6HP');
            `,
          }}
          id="google-analytics-inline-script" // Add unique ID for the inline script
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider> {/* Menambahkan ThemeProvider untuk mengakses tema */}
          <Navbar />
          {children} {/* Render konten utama aplikasi */}

          {/* Menambahkan TestimonialSlider atau komponen lainnya */}

          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
